const os = require('os')
console.log(os.homedir())
console.log(os.type())
console.log(os.freemem())
console.log(os.platform())
console.log(os.getPriority())
console.log(os.cpus())
console.log(os.networkInterfaces())
console.log(os.endianness())
console.log(os.setPriority())
console.log(os.uptime())
console.log(os.userInfo())
